services:
  plugin_hub:
    build: .
    ports:
      - "8787:8787"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=8787
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://local.hasura.dev:4318
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_LOG_LEVEL=DEBUG
      - OTEL_SERVICE_NAME=plugin_hub
      - LOG_LEVEL=debug
    command: npm run start:container
